
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/app/StoreProvider";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import FooterComponent from "@/components/footer/FooterComponent";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import {Suspense} from "react";
import Loading from "@/app/(user)/loading";
import SessionWrapper from "@/app/SessionWrapper";
import Error from "@/app/(user)/error";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    icons: {
        icon: "/assets/pic.jpg",
    },
    title: {
        template: "%s - MyShop",
        default: "MyShop"
    },
    description: "This is home page",
    keywords: ['shop', 'ecommerce', 'sell'],
    openGraph: {
        title: {
            template: "%s - MyShop",
            default: "MyShop"
        },
        description: "Generated by create next app",
        images:[
            "https://i.natgeofe.com/n/4f5aaece-3300-41a4-b2a8-ed2708a0a27c/domestic-dog_thumb_square.jpg"
        ]
    }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <SessionWrapper>
        <html lang="en">
        <body className={inter.className}>
        <StoreProvider>
          <header className='sticky top-0'>
            <NavbarComponent/>
          </header>
          <ErrorBoundary errorComponent={Error}>
            <Suspense fallback={<Loading/>}>{children}</Suspense>
          </ErrorBoundary>
          <footer>
            <FooterComponent/>
          </footer>
        </StoreProvider>
        </body>
        </html>
      </SessionWrapper>
  );
}
